name: Welcome ðŸ‘‹

permissions:
  issues: write
  pull-requests: write

on:
  pull_request:
    types: ["opened"]
  issues:
    types: ["opened"]

jobs:
  welcome:
    runs-on: ubuntu-20.04
    steps:
      - name: "Welcome ðŸ‘‹"
        uses: actions/first-interaction@v1.1.0
        with:
          issue-message: |
            Welcome, ${{github.actor}}! ðŸ‘‹
            Thanks for submitting your first issue! :rocket:
          pr-message: |
            Welcome, ${{github.actor}}! :wave:
            Thanks for submitting your first pull request! :rocket:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add label to first time contributoins
        uses: Code-Hex/first-label-interaction@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-labels: '["first time contribution"]'
          pr-labels: '["first time contribution"]'
